# Generated by Django 4.2 on 2023-07-18 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0002_hotelimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="featured_image",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 7, 18, 13, 19, 57, 444262, tzinfo=datetime.timezone.utc
                ),
                upload_to="images/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
