# Generated by Django 4.2 on 2023-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_hotel_featured_image_alter_room_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="featured_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
