# Generated by Django 4.2 on 2023-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specific_room_features',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preferences',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
